version: "3.1"

services:
  python_service:
    build: .
    volumes:
      - .:/root
    environment:
      - DB_HOST=db
      - DB_NAME=tl_data
      - DB_USER=develop
      - DB_PASSWORD=develop

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=tl_data
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=develop
      - MYSQL_PASSWORD=develop
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
      - "./schema.sql:/docker-entrypoint-initdb.d/1.sql"
    
    
volumes:
  db:
    driver: local
